### ISSUE TITLE
Configure Database

### ISSUE THREAD

**Issue by nilslee** [aaronlee232/notesage-electron#2]
**Feature**
Embedded SQLite Database for storing:
- Chat groups
- Messages
- pages
- page sections
- page tags

**Describe alternatives you've considered**
- Postgres Database via container
- Supabase Database via container

Chose Sqlite for lightweight and embedded nature

### Task List
- [x] Install SQLite modules
- [x] Configure Database tables
- [x] Integrate with Electron App

**Comment by aaronlee232** [comment]
```[tasklist]
### Database Task List
- [x] Install SQLite modules
- [x] Configure Database tables
- [x] Integrate with Electron App
```
