### ISSUE TITLE
Note Processing

### ISSUE THREAD

**Issue by nilslee** [aaronlee232/notesage-electron#3]
**Feature**
Process the each markdown file into sections that can be stored along with their embedding for later retrieval

Parse markdown tree and get sections based on heading sections.
Embedding needs to be serialized in order to be stored in SQLite database.

### Task List
- [x] Configure Node.js file system and notes directory
- [x] Add functionality to read all notes files
- [x] Add ability to process markdown file and generate embeddings
- [x] Integrate with database and upload processed markdown file data
- [x] Add re-processing feature when file add or change in directory detected
